name: CI

on:
  push:
    branches:
      - master
    paths:
      - '**.yml'
      - '**.ini'
      - '**.py'
      - '**.h'
      - '**.c'

jobs:
  build:
    # name: QIO
    strategy:
      fail-fast: false
      matrix:
        env:
          - debug
          - release
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip

      - name: Build
        if: success()
        run: |
          pio run -e ${{ matrix.env }} -d .

      - name: Upload
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.env }}_${{github.workflow}}
          path: ./.qio/build/${{ matrix.env }}/
